### ISSUE TITLE
ปัญหาการใช้ Interrupt GPIO 

### ISSUE THREAD

**Issue by Bomapisit** [TridentTD/TridentTD_EasyFreeRTOS32#3]
สวัสดีครับ TridentTD
ผมได้ใช้ TridentTD_EasyFreeRTOS32 ในการทำ multitask บน Esp32
ซึ่ง ในบาง Tast ผมมีการเขียน code รับค่า จาก Rotary Encode ซึ่งเป็นการเขียนแบบ Interrupt GPIO  ซึ่ง ก็สามารถเขียนรับค่าอะไรได้ปกติ 
เเต่ สิ่งที่แปลกคือใน GPIO อื่นๆ ที่ไม่มีส่วนเกี่ยวข้องนี้(ผมเขียนไฟกระพริบเอาไว้เเละต่อกับหลอด LED เขียนยุอีก Task หนึ่ง) ซึ่งปกติมันจะติด-ดับ เป็นจังหวะตามเงื่อนไขที่เขียนบน Task นั้น   เเต่เมื่อผมสร้าง Task ที่มีการเขียน Interrupt GPIO  ขึ้นมา กลับทำให้การทำงาน ของ หลอดไฟ LED ทำงานเพี้ยนผิดจังหวะไป ทั้งที่ สอง Task นี้ไม่ได้มีส่วนเกี่ยวข้องกัน  ผมเข้าใจว่า อาจจะเหมือนมีสัญญาณรบกวน เพราะเมื่อผมปิด Task  Interrupt GPIO ไป ตัว หลอด LED ก็ทำงานติดดับถูกต้องตามจังหวะเหมือนเดิม
ขอบคุณครับ

**Comment by TridentTD** [comment]
พึ่งเพ่ิม ความสามารถ เกี่ยวกับ INTERRUPTS ใน task เข้าไปให้

ลองทดสอบดูครับ

ตัวแปรที่เก็บค่า interrupt  ที่เป็นประเภท volatile นั้น
ก่อนที่มีการเพิ่มค่า หรือ ลดค่า หรือ copy มาไว้ตัวแปรจากตัวแปรเหล่านี้ไปไว้ตัวแปรธรรมดา

ให้ใส่คำสั่ง
NO_INTERRUPTS();

และ หลังจาก ที่ ลดค่า เพิ่มค่า หรือ copy ค่า
ก็ให้ใส่คำสั่ง 

INTERRUPTS();

ลองทดสอบดูครับ

**Comment by TridentTD** [comment]
ตัวอย่าง void ButtonInterrupt_task
ที่มีการใช้ INTERRUPTS() และ NO_INTERRUPTS() 

```c
/**********************************************
 * 
 * ตัวอย่าง Button Interrupt Task
 * 
 **********************************************/

#define BUTTON_PIN   0

volatile int vlt_ButtonCounter = 0;
void IRAM_ATTR handleButtonInterrupt();

void ButtonInterrupt_func(void*){
  int InterruptCount=0;
  VOID SETUP(){
    attachInterrupt( digitalPinToInterrupt(BUTTON_PIN), handleButtonInterrupt, FALLING);
  }
  VOID LOOP(){
    if( ButtonCounter > 0){
      NO_INTERRUPTS();                 // <------------------------------------
      vlt_ButtonCounter--;
      xButtonCounter =vlt_ButtonCounter;
      INTERRUPTS();                    // <------------------------------------
      Serial.printf("Button Count : %d\n", xButtonCounter );
      
      InterruptCount++;
      if( InterruptCount >= 5) {
        Serial.println("LED change status" );
        xLedState = !xLedState;   // กำหนดตัวแปร shared ระหว่าง task เปลี่ยนสถานะ LED
        InterruptCount = 0;
      }
    }
    DELAY(100);
  }
}

void IRAM_ATTR handleButtonInterrupt(){
  NO_INTERRUPTS();                 // <------------------------------------
  vlt_ButtonCounter++;
  INTERRUPTS();                    // <------------------------------------
}
```

สมมติมีอีก task เป็น LED task 
ที่จะเปลี่ยนสถานะ LED ตาม ButtonInterrupt task ข้างต้น

```c
/**********************************************
 * 
 * ตัวอย่าง LED task (ตามปกติทั่วไป)
 * 
 **********************************************/
#define LED_PIN     16

void LED_func(void*){
  VOID SETUP(){
    pinMode( LED_PIN, OUTPUT);
  }
  VOID LOOP(){
    digitalWrite(LED_PIN, xLedState);  // รับตัวแปร shared ระหว่าง task มาเปิดหรือปิดไฟ
    DELAY(10);
  }
}
```

ส่วนในหน้าหลัก มีการประกาศ task และ task functions ไปตามปกติ
```c
#include <TridentTD_EasyFreeRTOS32.h>

TridentOS ButtonInterrupt_task, LED_task;
void ButtonInterrupt_func(void*), LED_func(void*);

//------ Task-Shared Variables (x นำ)-----------
int   xButtonCounter=0;
bool  xLedState = false;
//----------------------------------------------

void setup() {
  Serial.begin(115200); Serial.println();
  ButtonInterrupt_task.start(ButtonInterrupt_func);
  LED_task.start(LED_func);
}

void loop() {}
```

**Comment by Bomapisit** [comment]
ขอบคุณครับกำลังลองครับ
