### ISSUE TITLE
ไม่ทราบว่าเราสามารถกำหนด  priority ของ Task นั้นๆ เเละ กำหนด ระยะเวลาการทำงานใน Task นั้นๆก่อนที่จะไปทำ Task อื่นๆได้หรือไม่ ครับ

### ISSUE THREAD

**Issue by Bomapisit** [TridentTD/TridentTD_EasyFreeRTOS32#4]

**Comment by ShinDaiIchi** [comment]
Version 1.1 นี้ ยังไม่ซับพอร์ต priority

ให้สร้างเป็น flag  ตัวแปรกลาง( x เล็กนำ) กำหนด แทนก็ได้ครับ
เช่น หาก flag ถูก task แรก กำหนดให้มีค่าเป็น true  
พอ task สอง พบค่า ก็ค่อยเริ่มทำงาน  เป็นต้น

**Comment by TridentTD** [comment]
Version 1.1 ยังไม่ได้ support เรื่องวิธีกำหนด Priority
ทาง multitask จะสลับให้เอง

วิธีสั่งให้ task1 ไปบอก task2 เริ่มทำงาน
อาจใช้การกำหนด ตัวแปร flag แชร์ระหว่าง task ไว้ที่หน้าหลัก
หาก flag ถูก task1 กำหนด เป็น true
เมื่อ task2 ตรวจพบ ก็ให้เริ่มทำงานที่ต้องการ
